### ISSUE TITLE
facing error in api

### ISSUE THREAD

**Issue by rizul11** [ruslanmv/Speech-to-Text-by-using-React#1]
in my console i am facing these : Error with Google Speech-to-Text API

**Comment by ruslanmv** [comment]
Hello, thank you for review the code, yes  I have still some issues but also some progress, I could fix the error  Error with Google Speech-to-Text API and I got the object , but without transcript. I think that the problem might be associated with the time of response or the query of response should modified.
The good thing is that the microphone works and the audio is in string form, moreover I splitted the code into two parts, the recording and the inference. If you see any other ideas hat you can give me to solve the issue , is welcome the ideas. :) 

![object](https://github.com/ruslanmv/Speech-to-Text-by-using-React/assets/51296249/2d7bb8b5-b889-4a7f-ad1c-bde803448629)
