### ISSUE TITLE
facing error in api - No transcription available

### ISSUE THREAD

**Issue by ruslanmv** [ruslanmv/Speech-to-Text-by-using-React#2]
I have the issue that the api does not have the transcription 
![object](https://github.com/ruslanmv/Speech-to-Text-by-using-React/assets/51296249/fcb83efa-bc61-4532-8063-0234d9d60d9c)

**Comment by rizul11** [comment]
Hi @ruslanmv do you know any other way to add Speech to text in react app , i already tried react-speech-recognition

**Comment by ruslanmv** [comment]
Finally, I could solve all the issues, and try again to copy the new code 💯
